services:
    mongo: # mongodb
        container_name: ${MONGO_HOST}
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        ports:
            - ${MONGO_PORT}:27017 # Comentar en producción para mayor seguridad
        volumes:
            #- ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - /data/db

    backend:
        build: .
        container_name: ${APP_HOST}
        restart: unless-stopped
        ports:
            - ${APP_PORT}:3000
        depends_on:
            - mongo
        volumes:
            - .:/app
            - /app/node_modules

volumes:
    mongodb_data: