services:
  mongo:
    container_name: ${MONGO_HOST}
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27018:27017"
    networks:
      - app-network

  backend:
    build: .
    container_name: ${APP_HOST}
    restart: unless-stopped
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PORT=27017
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge